import { nanoid } from "@reduxjs/toolkit";
const shapes = (corner, point) => {
  const shapesContainer = [
    {
      id: nanoid(10),
      shapeLength: 1,
      matris: [corner],
      isPlaced: false,
      rotation: [[corner]],
    },
    {
      id: nanoid(10),
      shapeLength: 3,
      deg: 2,
      isPlaced: false,
      rotation: [
        [corner, point, corner, 0, 0, 0, 0, 0, 0],
        [corner, 0, 0, point, 0, 0, corner, 0, 0],
      ],
      matris: [corner, point, corner, 0, 0, 0, 0, 0, 0],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, 0, 0, corner, corner, 0, 0, corner, 0],
      rotation: [
        [corner, 0, 0, corner, corner, 0, 0, corner, 0],
        [0, corner, corner, corner, corner, 0, 0, 0, 0],
        [corner, corner, 0, 0, corner, corner, 0, 0, 0],
        [0, corner, 0, corner, corner, 0, corner, 0, 0],
      ],

      isPlaced: false,
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, point, corner, 0, corner, 0, 0, 0, 0],
      isPlaced: false,
      rotation: [
        [corner, point, corner, 0, corner, 0, 0, 0, 0],
        [corner, 0, 0, point, corner, 0, corner, 0, 0],
        [0, corner, 0, corner, point, corner, 0, 0, 0],
        [0, corner, 0, corner, point, 0, 0, corner, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [0, corner, 0, corner, point, corner, 0, corner, 0],
      rotation: [
        [0, corner, 0, corner, point, corner, 0, corner, 0],
        [0, corner, 0, corner, point, corner, 0, corner, 0],
        [0, corner, 0, corner, point, corner, 0, corner, 0],
        [0, corner, 0, corner, point, corner, 0, corner, 0],
      ],
      isPlaced: false,
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, corner, 0, point, 0, 0, corner, corner, 0],
      rotation: [
        [corner, corner, 0, point, 0, 0, corner, corner, 0],
        [corner, 0, corner, corner, point, corner, 0, 0, 0],
        [corner, corner, 0, 0, point, 0, corner, corner, 0],
        [corner, point, corner, corner, 0, corner, 0, 0, 0],
      ],
      isPlaced: false,
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, point, corner, corner, 0, 0, 0, 0, 0],
      rotation: [
        [corner, 0, 0, point, 0, 0, corner, corner, 0],
        [0, 0, corner, corner, point, corner, 0, 0, 0],
        [corner, point, corner, corner, 0, 0, 0, 0, 0],
        [corner, corner, 0, 0, point, 0, 0, corner, 0],
        [corner, corner, 0, point, 0, 0, corner, 0, 0],
      ],
      isPlaced: false,
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, corner, 0, 0, point, 0, 0, corner, corner],
      isPlaced: false,
      rotation: [
        [corner, corner, 0, 0, point, 0, 0, corner, corner],
        [0, 0, corner, corner, point, corner, corner, 0, 0],
        [0, corner, corner, 0, point, 0, corner, corner, 0],
        [corner, 0, 0, corner, point, corner, 0, 0, corner],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, point, corner, point, 0, 0, corner, 0, 0],
      isPlaced: false,
      rotation: [
        [corner, point, corner, point, 0, 0, corner, 0, 0],
        [corner, 0, 0, point, 0, 0, corner, point, corner],
        [0, 0, corner, 0, 0, point, corner, point, corner],
        [corner, point, corner, 0, 0, point, 0, 0, corner],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 2,
      matris: [corner, 0, corner, 0],
      isPlaced: false,
      rotation: [
        [corner, 0, corner, 0],
        [corner, corner, 0, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 4,
      matris: [
        0,
        0,
        corner,
        0,
        corner,
        point,
        point,
        corner,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      isPlaced: false,
      rotation: [
        [0, 0, corner, 0, corner, point, point, corner, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, point, point, corner, 0, corner, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, 0, 0, 0, point, 0, 0, 0, point, corner, 0, 0, corner, 0, 0, 0],

        [0, corner, 0, 0, 0, point, 0, 0, corner, point, 0, 0, 0, corner, 0, 0],
        [corner, point, point, corner, 0, , corner, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, 0, 0, 0, point, corner, 0, 0, point, 0, 0, 0, corner, 0, 0, 0],

        [0, corner, 0, 0, corner, point, point, corner, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, corner, 0, 0, corner, point, 0, 0, 0, point, 0, 0, 0, corner, 0, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 2,
      matris: [corner, corner, 0, corner],
      isPlaced: false,
      rotation: [
        [corner, corner, 0, corner],
        [corner, corner, corner, 0],
        [corner, 0, corner, corner],
        [0, corner, corner, corner],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 2,
      matris: [corner, corner, corner, corner],
      isPlaced: false,
      rotation: [[corner, corner, corner, corner]],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, point, corner, 0, point, 0, 0, corner, 0],
      isPlaced: false,
      rotation: [
        [corner, point, corner, 0, point, 0, 0, corner, 0],
        [corner, 0, 0, point, point, corner, corner, 0, 0],
        [0, corner, 0, 0, point, 0, corner, point, corner],
        [0, 0, corner, corner, point, point, 0, 0, corner],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, 0, 0, corner, point, corner, 0, corner, 0],
      isPlaced: false,
      rotation: [
        [corner, 0, 0, corner, point, corner, 0, corner, 0],
        [0, corner, 0, 0, point, corner, corner, corner, 0],
        [0, corner, 0, corner, point, corner, corner, 0, 0],
        [0, corner, 0, corner, point, 0, 0, corner, corner],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, point, corner, 0, corner, corner, 0, 0, 0],
      isPlaced: false,
      rotation: [
        [corner, point, corner, 0, corner, corner, 0, 0, 0],
        [corner, corner, 0, point, corner, 0, corner, 0, 0],
        [corner, point, 0, corner, point, corner, 0, 0, 0],
        [corner, point, corner, corner, point, 0, 0, 0, 0],
        [0, corner, corner, corner, point, corner, 0, 0, 0],
        [corner, corner, 0, point, corner, 0, 0, corner, 0],
        [corner, 0, 0, point, corner, 0, corner, corner, 0],
        [0, corner, 0, point, corner, 0, corner, corner, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 3,
      matris: [corner, corner, 0, 0, corner, corner, 0, 0, corner],
      isPlaced: false,
      rotation: [
        [corner, corner, 0, 0, corner, corner, 0, 0, corner],
        [0, corner, corner, corner, corner, 0, corner, 0, 0],
        [corner, 0, 0, corner, corner, 0, 0, corner, corner],
        [0, 0, corner, 0, corner, corner, corner, corner, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 4,
      matris: [
        corner,
        point,
        point,
        corner,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      isPlaced: false,
      rotation: [
        [corner, point, point, corner, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, 0, 0, 0, point, 0, 0, 0, point, 0, 0, 0, corner, 0, 0, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 4,
      matris: [
        corner,
        point,
        point,
        corner,
        corner,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      isPlaced: false,
      rotation: [
        [corner, point, point, corner, corner, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, point, point, corner, corner, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [corner, 0, 0, 0, corner, point, point, corner, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, corner, corner, point, point, corner, 0, 0, 0, 0, 0, 0, 0, 0],

        [corner, corner, 0, 0, point, 0, 0, 0, point, 0, 0, 0, corner, 0, 0, 0],
        [corner, corner, 0, 0, 0, point, 0, 0, 0, point, 0, 0, 0, corner, 0, 0],
        [corner, 0, 0, 0, point, 0, 0, 0, point, 0, 0, 0, corner, corner, 0, 0],
        [0, corner, 0, 0, 0, point, 0, 0, 0, point, 0, 0, corner, corner, 0, 0],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 5,
      matris: [
        corner,
        point,
        corner,
        0,
        0,
        0,
        0,
        point,
        0,
        0,
        0,
        0,
        corner,
        point,
        corner,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      isPlaced: false,
      rotation: [
        [
          corner,
          point,
          corner,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          corner,
          point,
          corner,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
        ],
        [
          0,
          0,
          corner,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          corner,
          point,
          corner,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          corner,
          0,
          0,
          0,
          0,
        ],
        [
          0,
          0,
          corner,
          point,
          corner,
          0,
          0,
          point,
          0,
          0,
          corner,
          point,
          corner,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
        ],
        [
          corner,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          corner,
          point,
          corner,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          corner,
          0,
          0,
        ],
      ],
    },

    {
      id: nanoid(10),
      shapeLength: 5,
      matris: [
        corner,
        point,
        point,
        point,
        corner,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      isPlaced: false,
      rotation: [
        [
          corner,
          point,
          point,
          point,
          corner,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
        ],
        [
          corner,
          0,
          0,
          0,
          0,

          point,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          point,
          0,
          0,
          0,
          0,
          corner,
          0,
          0,
          0,
          0,
        ],
      ],
    },
  ];
  return shapesContainer;
};
export default shapes;
